### ISSUE TITLE
[Bug Report] - Change Common JS Module Syntax into ES Module Syntax for "prism-react-renderer" in the "docusaurus.config.js" and resolve error when running "docusaurus start" command

### ISSUE THREAD

**Issue by devilkiller-ag** [uptane/uptane.github.io#139]
### Describe the bug.

Currently the import for `prism-react-renderer` is in the Common JS Module Style in the [docusaurus.config.js ](https://github.com/uptane/uptane.github.io/blob/main/docusaurus.config.js)file:
```
const { themes } = require('prism-react-renderer');
```
We should change this into into ES Module Syntax as mentioned in its [documentation](https://www.npmjs.com/package/prism-react-renderer):
```
import { themes } from 'prism-react-renderer';
```

Currently following lines 
```
const lightTheme = themes.github;
const darkTheme = themes.dracula;
``` 
are causing error when we run "yarn start" error:

```
$ yarn start
yarn run v1.22.19
$ docusaurus start
[INFO] Starting the development server...
[ERROR] TypeError: Cannot read properties of undefined (reading 'github')
    at Object.<anonymous> (/home/devilkillerag/Documents/OpenSource/uptane-website/docusaurus.config.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at module.exports (/home/devilkillerag/Documents/OpenSource/uptane-website/node_modules/import-fresh/index.js:32:59)
    at loadSiteConfig (/home/devilkillerag/Documents/OpenSource/uptane-website/node_modules/@docusaurus/core/lib/server/config.js:36:55)
    at async loadContext (/home/devilkillerag/Documents/OpenSource/uptane-website/node_modules/@docusaurus/core/lib/server/index.js:31:63)
    at async load (/home/devilkillerag/Documents/OpenSource/uptane-website/node_modules/@docusaurus/core/lib/server/index.js:74:21)
[INFO] Docusaurus version: 2.4.3
Node version: v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Abhijay007** [comment]
@devilkiller-ag  I believe it's okay based on the Docusaurus documentation found here: https://docusaurus.io/docs/migration/v3#prism-react-renderer-v20. However, it could potentially conflict with your local setup. Can you please verify whether you've updated your setup according to Docusaurus v3? We've recently migrated our site to v3.

**Comment by Abhijay007** [comment]
> [INFO] Docusaurus version: 2.4.3
> Node version: v18.13.0
> error Command failed with exit code 1.

as you can see it is still version 2.4.3 for your machine, you might need to run the latest pull

**Comment by Abhijay007** [comment]
closed as resolved
